Repository auth0/auth0-python, pull requests merged in 2018-11, with the labels that each got.

#167 Stop lower-casing email on user search
  auth0/v3/management/users_by_email.py
  auth0/v3/test/management/test_users_by_email.py
Labels: CH: Fixed

#165 Add snyk policy file to ignore unaffected vulnerable packages
  .snyk
Labels: CH: Security

#170 Add Revoke Refresh Token endpoint
  auth0/v3/authentication/revoke_token.py
  auth0/v3/test/authentication/test_revoke_token.py
Labels: CH: Added
