Repository auth0/auth0-python, pull requests merged in 2021-08, with the labels that each got.

#279 Add Passwordless Login function
  auth0/v3/authentication/get_token.py
  auth0/v3/authentication/passwordless.py
  auth0/v3/test/authentication/test_get_token.py
  auth0/v3/test/authentication/test_passwordless.py
Labels: CH: Added, review:small

#280 Deprecate /oauth/ro for passwordless
  auth0/v3/authentication/passwordless.py
Labels: CH: Deprecated, review:tiny

#285 [SDK-2687] Implement automatic rate-limit handling
  auth0/v3/management/auth0.py
  auth0/v3/management/blacklists.py
  auth0/v3/management/client_grants.py
  auth0/v3/management/clients.py
  auth0/v3/management/connections.py
  auth0/v3/management/custom_domains.py
  auth0/v3/management/device_credentials.py
  auth0/v3/management/email_templates.py
  auth0/v3/management/emails.py
  auth0/v3/management/grants.py
  auth0/v3/management/guardian.py
  auth0/v3/management/hooks.py
  auth0/v3/management/jobs.py
  auth0/v3/management/log_streams.py
  auth0/v3/management/logs.py
  auth0/v3/management/organizations.py
  auth0/v3/management/resource_servers.py
  auth0/v3/management/rest.py
  auth0/v3/management/roles.py
  auth0/v3/management/rules.py
  auth0/v3/management/rules_configs.py
  auth0/v3/management/stats.py
  auth0/v3/management/tenants.py
  auth0/v3/management/tickets.py
  auth0/v3/management/user_blocks.py
  auth0/v3/management/users.py
  auth0/v3/management/users_by_email.py
  auth0/v3/test/management/test_blacklists.py
  auth0/v3/test/management/test_client_grants.py
  auth0/v3/test/management/test_clients.py
  auth0/v3/test/management/test_connections.py
  auth0/v3/test/management/test_custom_domains.py
  auth0/v3/test/management/test_device_credentials.py
  auth0/v3/test/management/test_email_endpoints.py
  auth0/v3/test/management/test_emails.py
  auth0/v3/test/management/test_grants.py
  auth0/v3/test/management/test_guardian.py
  auth0/v3/test/management/test_hooks.py
  auth0/v3/test/management/test_jobs.py
  auth0/v3/test/management/test_log_streams.py
  auth0/v3/test/management/test_logs.py
  auth0/v3/test/management/test_organizations.py
  auth0/v3/test/management/test_resource_servers.py
  auth0/v3/test/management/test_rest.py
  auth0/v3/test/management/test_roles.py
  auth0/v3/test/management/test_rules.py
  auth0/v3/test/management/test_rules_configs.py
  auth0/v3/test/management/test_stats.py
  auth0/v3/test/management/test_tenants.py
  auth0/v3/test/management/test_tickets.py
  auth0/v3/test/management/test_user_blocks.py
  auth0/v3/test/management/test_users.py
  auth0/v3/test/management/test_users_by_email.py
Labels: CH: Added, review:large

#290 Release 3.18.0
  CHANGELOG.md
  auth0/__init__.py
Labels: tiny
