Repository auth0/auth0-python, pull requests merged in 2022-03, with the labels that each got.

#301 [SDK-3174] Add `DELETE` method for `/api/v2/users/{id}/authenticators` endpoint
  auth0/v3/management/users.py
  auth0/v3/test/management/test_users.py
Labels: CH: Added

#273 [SDK-3175] Return token claims in TokenVerifier.verify()
  auth0/v3/authentication/token_verifier.py
  auth0/v3/test/authentication/test_token_verifier.py
Labels: CH: Changed

#310 Release 3.22.0
  CHANGELOG.md
  auth0/__init__.py
Labels: review:small
